### ISSUE TITLE
Pull request build is failing

### ISSUE THREAD

**Issue by sergiocabral** [progit/progit2-pt-br#111]
For a few months now, the build of pull requests is failing.
Below is the error log of the last build.
I'll try to analyze it as soon as possible, but as I'm not yet inside the code, it will take some time.
But if you, @jnavila, think it's easy to solve... I appreciate it.

Printscreen of error: [https://imgur.com/a/RkCo164](https://imgur.com/a/RkCo164)

```
Run bundle exec rake book:build_action
To use retry middleware with Faraday v2.0+, install `faraday-retry` gem
Generating contributors list

Converting to HTML...

 -- HTML output at progit.html
 -- Validate HTML file progit.html
/home/runner/work/progit2-pt-br/progit2-pt-br/vendor/bundle/ruby/2.7.0/gems/mercenary-0.[4](https://github.com/progit/progit2-pt-br/runs/7956228467?check_suite_focus=true#step:7:5).0/lib/mercenary/program.rb:33:in `go': invalid option: --check-html (OptionParser::InvalidOption)
Did you mean?  checks
	from /home/runner/work/progit2-pt-br/progit2-pt-br/vendor/bundle/ruby/2.7.0/gems/mercenary-0.4.0/lib/mercenary.rb:21:in `program'
	from /home/runner/work/progit2-pt-br/progit2-pt-br/vendor/bundle/ruby/2.7.0/gems/html-proofer-4.4.0/bin/htmlproofer:11:in `<top (required)>'
	from /home/runner/work/progit2-pt-br/progit2-pt-br/vendor/bundle/ruby/2.7.0/bin/htmlproofer:23:in `load'
	from /home/runner/work/progit2-pt-br/progit2-pt-br/vendor/bundle/ruby/2.7.0/bin/htmlproofer:23:in `<top (required)>'
	from /opt/hostedtoolcache/Ruby/2.7.6/x64/lib/ruby/gems/2.7.0/gems/bundler-2.3.20/lib/bundler/cli/exec.rb:[5](https://github.com/progit/progit2-pt-br/runs/7956228467?check_suite_focus=true#step:7:6)8:in `load'
	from /opt/hostedtoolcache/Ruby/2.7.[6](https://github.com/progit/progit2-pt-br/runs/7956228467?check_suite_focus=true#step:7:7)/x64/lib/ruby/gems/2.[7](https://github.com/progit/progit2-pt-br/runs/7956228467?check_suite_focus=true#step:7:8).0/gems/bundler-2.3.20/lib/bundler/cli/exec.rb:5[8](https://github.com/progit/progit2-pt-br/runs/7956228467?check_suite_focus=true#step:7:9):in `kernel_load'
	from /opt/hostedtoolcache/Ruby/2.7.6/x64/lib/ruby/gems/2.7.0/gems/bundler-2.3.20/lib/bundler/cli/exec.rb:23:in `run'
	from /opt/hostedtoolcache/Ruby/2.7.6/x64/lib/ruby/gems/2.7.0/gems/bundler-2.3.20/lib/bundler/cli.rb:485:in `exec'
	from /opt/hostedtoolcache/Ruby/2.7.6/x64/lib/ruby/gems/2.7.0/gems/bundler-2.3.20/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /opt/hostedtoolcache/Ruby/2.7.6/x64/lib/ruby/gems/2.7.0/gems/bundler-2.3.20/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /opt/hostedtoolcache/Ruby/2.7.6/x64/lib/ruby/gems/2.7.0/gems/bundler-2.3.20/lib/bundler/vendor/thor/lib/thor.rb:3[9](https://github.com/progit/progit2-pt-br/runs/7956228467?check_suite_focus=true#step:7:10)2:in `dispatch'
	from /opt/hostedtoolcache/Ruby/2.7.6/x64/lib/ruby/gems/2.7.0/gems/bundler-2.3.20/lib/bundler/cli.rb:31:in `dispatch'
	from /opt/hostedtoolcache/Ruby/2.7.6/x64/lib/ruby/gems/2.7.0/gems/bundler-2.3.20/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	from /opt/hostedtoolcache/Ruby/2.7.6/x64/lib/ruby/gems/2.7.0/gems/bundler-2.3.20/lib/bundler/cli.rb:25:in `start'
	from /opt/hostedtoolcache/Ruby/2.7.6/x64/lib/ruby/gems/2.7.0/gems/bundler-2.3.20/exe/bundle:48:in `block in <top (required)>'
	from /opt/hostedtoolcache/Ruby/2.7.6/x64/lib/ruby/gems/2.7.0/gems/bundler-2.3.20/lib/bundler/friendly_errors.rb:[12](https://github.com/progit/progit2-pt-br/runs/7956228467?check_suite_focus=true#step:7:13)0:in `with_friendly_errors'
	from /opt/hostedtoolcache/Ruby/2.7.6/x64/lib/ruby/gems/2.7.0/gems/bundler-2.3.20/exe/bundle:36:in `<top (required)>'
	from /opt/hostedtoolcache/Ruby/2.7.6/x64/bin/bundle:23:in `load'
	from /opt/hostedtoolcache/Ruby/2.7.6/x64/bin/bundle:23:in `<main>'
rake aborted!
'bundle exec htmlproofer --check-html --report-mismatched-tags progit.html' failed
/home/runner/work/progit2-pt-br/progit2-pt-br/Rakefile:9:in `exec_or_raise'
/home/runner/work/progit2-pt-br/progit2-pt-br/Rakefile:93:in `build_book'
/home/runner/work/progit2-pt-br/progit2-pt-br/Rakefile:[13](https://github.com/progit/progit2-pt-br/runs/7956228467?check_suite_focus=true#step:7:14)1:in `block (2 levels) in <top (required)>'
/home/runner/work/progit2-pt-br/progit2-pt-br/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
/opt/hostedtoolcache/Ruby/2.7.6/x64/bin/bundle:[23](https://github.com/progit/progit2-pt-br/runs/7956228467?check_suite_focus=true#step:7:24):in `load'
/opt/hostedtoolcache/Ruby/2.7.6/x64/bin/bundle:23:in `<main>'
Tasks: TOP => book:build_action
(See full trace by running task with --trace)
htmlproofer 4.4.0 | Error:  Whoops, we can't understand your command.
htmlproofer 4.4.0 | Error:  invalid option: --check-html
Did you mean?  checks
htmlproofer 4.4.0 | Error:  Run your command again with the --help switch to see available options.
Error: Process completed with exit code 1.
```

**Comment by sergiocabral** [comment]
O erro registrado aqui pertencia ao fluxo antigo de build e permaneceu como um bloqueio importante para novas contribuições. O PR #138 substituiu essa infraestrutura pela base atual: a CI do PR passou e a publicação da master gerou a release 2.1.49 com HTML, EPUB, FB2 e PDF. O build voltou a funcionar, então esta issue pode ser encerrada como concluída.
